### ISSUE TITLE
[BE] typo in names 

### ISSUE THREAD

**Issue by kbojarowska** [kbojarowska/SkinResque#97]
In models you have:
![image](https://user-images.githubusercontent.com/83237280/209558903-23bc1705-0239-46ec-8e2e-c4e0b5c0ce3f.png)
![image](https://user-images.githubusercontent.com/83237280/209559007-c6879619-f41b-40eb-ad06-c9f82eedaf36.png)
And in schema:
![image](https://user-images.githubusercontent.com/83237280/209558935-8d4800ed-c066-4b35-9171-787160f24a46.png)
![image](https://user-images.githubusercontent.com/83237280/209558977-ad42bf07-43f9-4b3d-b9d5-3b0e45dbd301.png)

**Comment by MrSpaceMan1** [comment]
Already been taken care of on a branch I'm currently working on
